name: "PHPUnit"
on:
  push:
  pull_request_target:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - '8.0'
          - '8.1'

    name: PHP ${{ matrix.php_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with pecl extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: :opcache
      - run: composer install
      - run: vendor/bin/phpunit
